[gcp_service_account]
type = "service_account"
project_id = "robintracker"
private_key_id = "dd5c338448050580bbfa87424e43214ba5e8402d"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDwU6glWlDdNFu1
ZoUmSEC7rqKOOpLiB5pkPaLIg260zR5XUU4/dt0PJ4pxZkUGwoQ9HkR19v52kyTe
t8f32CXHCteMLb9u3tMT0rI8mhNmJQGiJe5/fa9Q+ZqYM4LaEFDPfky7M1InumqZ
pQKfJdv4usaut7KnAp2P63ZPX4pOtcQuKi8iFshWHpKZnoaV0P+ad4TEcgrYuRBg
49HPAicw1QZCct6XdrQ6ZZ3s58xjjgLdFbWknKi88KuPqNcPVoU+6VVEjE0PJi4z
S8dJEQ42A5GEiiJsDByJY7wfh0xTryqeD1/xp2c0GstIETIrd3zNaTCTVu8avSbJ
7efuufgZAgMBAAECggEAJhI6muA52zEGLjB1e2EK0DCUE8/3oNLvhF23QeiASygL
XG3G5Yrg7hundNtsp+t8o2n+Emn0WbhpqNaYWQzmvydaihxdLSUjbwp7rdoCpLXM
EnHL3Gp+sWc5NE9EtWLMSnKJmUZCB4UiigB379pBhJ+iBd+X75kceMYmUeCiumEG
gcZ26LY1CKikLhqGvCrFfQl1Zlh8teNXr/JGlD6ucLBEUuA2mQFTw7oCP4xv++lA
gCupAes3ECfJ92sPtForn/O5KGWGn3IeB5z+R3A9PJdks1sBmUqGFgW7SYuJHgMI
9oVOOUoyAiZLCO2w3wtdCBQ4UiBuXrZ0VTQwf9/r+QKBgQD6YvpiXxboXSaQTojN
UcKCzD1WQrI0lZRQt7yWe+a7vj6/ARbW9NB7kpgkMJIA9UWwgrb3Q4g8x8/B+jvY
XyLip0O+FZwteKaPB3LUyrDflyctVTV/fCLuLRtrsGV5XQb9elYYIYTSMiSdy0Uw
v9kXiR4nwGurQOye3CnFooJ22wKBgQD1tvFyiJTqHDziBa39v7RL/MIirQCcwBv7
Gq4Mj2O/5HDF65Xj/8KPIUYad8TRF/LlYOzX/BMqItLXjbUEnuUTOjV3t3o7k1L0
TCxxLRcHl0zM3VM7ak96ZHk0GF1hsg3w1j3S60xFgGaW2I5qJlLkBeCZtMSwBa+D
QI4XP9P9GwKBgQCqaz+8QLhYwz4CLlHSXXmkiNqeoZqlS8G9BrGnQwGSezQ90MH4
4Hwd/3Lp/t0BJe+e6fkaZq6Nn/n6LxUYefhGiE4FTLQWBu5mn007JBIqvLh/lGVr
NdSYg78MFu2aIwUk9WUv23CJmHNvqvCW850Q9dS+fatKzk+++F6+E5P0zQKBgQCp
6oC9O0X/Pte7VUIkn1UG1xtI72nk+9RdqO2DMgVAxbBWrbtRl6PrZo8b7obkMTN+
+6/NDDwUf1BeT1hGgbrXuQEQcIjOeep7ldGF0jCCx1YMtWDBTZr4gFJwfAjXblHF
oeHO4Xg09735wnd5YFch6A6RPDhnoQbmNNYNrc3i0QKBgQCw1Brzp5HqriEQMg5d
HVFjbCpOA1RzMp8a4SMbOAguRegcqluUbhKCG4KmbPo0F6e8Ie99+cP0fZhI2Z5a
VPJAdgSA+vZz2o6n45gwqrWKIRHDjdM5Sl9ZRN8fyQ4vLp3elvpkNAzfwcYmqYdR
K9WBruo4g1qujj6C/pNdC3NMXQ==
-----END PRIVATE KEY-----
"""
client_email = "streamlit-sheet-bot@robintracker.iam.gserviceaccount.com"
client_id = "110545545423469155060"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-sheet-bot%40robintracker.iam.gserviceaccount.com"
universe_domain = "googleapis.com"